name: Linux ARM64
on:
  - push
  - pull_request
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          # Add arm64 sources
          sudo tee /etc/apt/sources.list.d/arm.list > /dev/null <<EOF
          deb [arch=arm64] http://ports.ubuntu.com/ jammy main restricted
          deb [arch=arm64] http://ports.ubuntu.com/ jammy-updates main restricted
          deb [arch=arm64] http://ports.ubuntu.com/ jammy universe
          deb [arch=arm64] http://ports.ubuntu.com/ jammy-updates universe
          deb [arch=arm64] http://ports.ubuntu.com/ jammy multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ jammy-updates multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ jammy-backports main restricted universe multiverse
          EOF
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu gettext
          # Remove conflicting packages
          sudo apt remove -y libglib2.0-dev
          sudo dpkg --add-architecture arm64
          # We only need these to build, not to run.  Skip the dependency check.
          sudo apt download libpurple0:arm64 libpurple-dev:arm64 libglib2.0-dev:arm64 libjson-glib-dev:arm64 libjson-glib-1.0-0:arm64 zlib1g-dev:arm64
          sudo dpkg --force-depends -i *_arm64.deb *_arm64.deb

      - name: make
        run: |
          export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/aarch64-linux-gnu/pkgconfig/
          export CC=aarch64-linux-gnu-gcc
          make
          file libchatgpt.so
          mv libchatgpt.so libchatgpt_arm64.so

      - name: archive
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with: 
            name: plugin 
            path: lib*.so

      - name: release
        if: ${{ !env.ACT }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: lib*.so
          tag: nightly-${{ github.sha }}
          name: Nightly ${{ github.sha }}
          allowUpdates: true
          makeLatest: true

      - name: attest
        if: ${{ !env.ACT }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: lib*.so
