name: Linux
on:
  - push
  - pull_request
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          sudo apt update
          sudo apt install -y libglib2.0-dev libjson-glib-dev gettext libpurple-dev libpurple0
      - name: make
        run: make

      - name: archive
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with: 
            name: plugin 
            path: lib*.so

      - name: release
        if: ${{ !env.ACT }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: lib*.so
          tag: nightly-${{ github.sha }}
          name: Nightly ${{ github.sha }}
          allowUpdates: true
          makeLatest: true

      - name: attest
        if: ${{ !env.ACT && github.repository_visibility == 'public' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: lib*.so
