name: Linux ARM64
on:
  - push
  - pull_request
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          # Add arm64 sources for Noble (24.04)
          sudo tee /etc/apt/sources.list.d/arm.list > /dev/null <<EOF
          deb [arch=arm64] http://ports.ubuntu.com/ noble main restricted
          deb [arch=arm64] http://ports.ubuntu.com/ noble-updates main restricted
          deb [arch=arm64] http://ports.ubuntu.com/ noble universe
          deb [arch=arm64] http://ports.ubuntu.com/ noble-updates universe
          deb [arch=arm64] http://ports.ubuntu.com/ noble multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ noble-updates multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ noble-backports main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ noble-security main restricted universe multiverse
          EOF
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu gettext pkg-config
          
          # Install arm64 development libraries
          sudo apt install -y libpurple0:arm64 libpurple-dev:arm64 libglib2.0-dev:arm64 libjson-glib-dev:arm64 zlib1g-dev:arm64

      - name: make
        run: |
          export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
          export CC=aarch64-linux-gnu-gcc
          export PKG_CONFIG=aarch64-linux-gnu-pkg-config
          make
          file libaichat.so
          mv libaichat.so libaichat_arm64.so

      - name: archive
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with: 
            name: plugin 
            path: lib*.so

      - name: release
        if: ${{ !env.ACT }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: lib*.so
          tag: nightly-${{ github.sha }}
          name: Nightly ${{ github.sha }}
          allowUpdates: true
          makeLatest: true

      - name: attest
        if: ${{ !env.ACT }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: lib*.so